# Generated by Django 4.2.7 on 2024-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
